name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout pull request
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to access base commit

      - name: 📄 Prepare README files
        run: |
          mkdir -p base head

          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          echo "BASE SHA: $BASE_SHA"
          echo "HEAD SHA: $HEAD_SHA"

          # Get README from base and head
          git show $BASE_SHA:README.md > base/README.md || exit 1
          git show $HEAD_SHA:README.md > head/README.md || exit 1

      - name: 📝 Check modified files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          if [ "$(echo "$CHANGED_FILES" | wc -l)" -ne 1 ] || [ "$CHANGED_FILES" != "README.md" ]; then
            echo "::error::Only README.md should be modified. Found changes in: $CHANGED_FILES"
            exit 1
          fi

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: pip install lxml requests beautifulsoup4 markdown

      - name: 🧪 Run validation script
        run: python .github/workflows/validate_pr.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  auto-merge:
    needs: validate-pull-request
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: 🔀 Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
