name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo (HEAD)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if base and head branches exist
        run: |
          for BRANCH in ${{ github.base_ref }} ${{ github.head_ref }}; do
            if ! git ls-remote --exit-code origin refs/heads/$BRANCH; then
              echo "::error::❌ Branch '$BRANCH' does not exist."
              exit 1
            fi
          done

      - name: Prepare README files from base and head
        run: |
          mkdir -p base head
          git fetch origin ${{ github.base_ref }}
          git show origin/${{ github.base_ref }}:README.md > base/README.md
          cp README.md head/README.md

      - name: Ensure only README.md is modified
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "📄 Changed files:"
          echo "$CHANGED_FILES"
          for file in $CHANGED_FILES; do
            if [ "$file" != "README.md" ]; then
              echo "::error file=$file::❌ Only README.md should be modified. You modified: $file"
              exit 1
            fi
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install lxml requests beautifulsoup4 markdown

      - name: Run validation script
        run: python .github/workflows/validate_pr.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  auto-merge:
    needs: validate-pull-request
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
